version: "3"

networks:
  my-network:
    external: true

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
    - my-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
    - my-network

  api:
    build:
      context: ./main_api
      dockerfile: ./Docker/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./main_api:/api
    networks:
    - my-network
    depends_on:
      - database

  ms_mailer:
    build:
      context: ./ms_mailer
      dockerfile: ./Docker/Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./ms_mailer:/app
    networks:
      - my-network
    depends_on:
      - kafka

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_kafka
    ports:
      - "5430:5432"
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
    networks:
      - my-network

volumes:
  pg_data:
  ms_mailer:
  main_api:
